name: where
description: A Flutter based Mobile Application getting time, latitude, longitude & velocity with the help of GPS Sensor and three dimensional values of gravity based acceleration (G).

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager: any
  hive:
  hive_flutter: ^0.2.1
  baseflow_plugin_template:
    git:
      url: git://github.com/Baseflow/baseflow_plugin_template.git
      ref: v2.0.0-nullsafety  
  flutter_background_service: any
  geolocator: any
  geolocation:
  kdgaugeview: ^1.0.2
  connectivity: any
  intl: ^0.16.1
  speedometer: ^1.0.8
  google_maps_flutter: ^1.0.6
  location: any
  sensors: ">=0.4.2+6 <2.0.0"
  uuid: any
#  shared_preferences: ^0.4.3
  flutter_simple_dependency_injection: ^1.0.1 #to perform dependency injection
  flutter_file_manager: ^0.2.0
  #firebase_core: "0.7.0"
  #firebase_auth: ^1.0.1
  #cloud_firestore: ^1.0.1
  #firebase_database: ^6.0.0
  dio: any
  permission_handler: ^4.4.0
  ext_storage: any
  shared_preferences: any
  flutter_string_encryption: ^0.3.1  
  csv: any
  sqflite: ^1.1.7+1
  path_provider: any
  cryptography: any
  flutter_local_notifications: any
  awesome_notifications: any
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
      ref: 2.0.0-dev.1
  flutter_barcode_scanner: ^1.0.2
  http: any 
  path: ^1.6.4
  cron: ^0.3.0
  scoped_model: ^1.0.1
  country_code_picker: any
  email_validator: any
  bluetooth_enable: any
  form_field_validator: any
  #flutter_blue: any

  flutter_blue_beacon:
   # path: ../
  flutter_blue: ^0.5.0
  flutter_beacon:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

  flutter_bluetooth_serial:
  hive_generator: ^0.5.1
  build_runner:
  flutter_restart: any
   # path: ../  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
dependency_overrides:
  platform: ^3.1.0
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/login_fig.png
    - images/register_fig.png
    - images/verify_fig.png
    - images/picture_fig.jpg
    - images/forgot_fig.png
    - images/reset_fig.png
    - images/check1.png
    - images/check-circle.gif
    - images/location.gif
    - images/status.gif
    - images/contact1.jpg
    - images/diagnosis.png
    - images/smartphone.png
    - images/3856337.png
    - images/contact-tracing.png
    - images/Flat_tick_icon.png
    - images/Contact_tracing.jfif
    - images/appbackground.jfif
    - images/setting.png
    - images/background_Image.png
    - images/blue.png
  # To add assets to your application, add an assets section, like this:
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages